import '../models/meal.dart';

final kMeals = <Meal>[
  Meal(
    id: 1,
    categories: [1, 2],
    title: 'Espaguete com Molho de Tomate',
    cost: Cost.cheap,
    complexity: Complexity.simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg/800px-Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg',
    duration: 20,
    ingredients: [
      '4 Tomates',
      '1 Colher de sopa de azeite',
      '1 Cebola',
      '250g Espaguete',
      'Tempero a gosto',
      'Queijo (opcional)'
    ],
    steps: [
      'Corte os tomates e a cebola em pequenos pedaços.',
      'Ferva um pouco de água - adicione sal quando ferver.',
      'Coloque o espaguete na água fervente - deve ser feito em cerca de 10 a 12 minutos.',
      'Enquanto isso, aqueça um pouco de azeite e adicione a cebola cortada.',
      'Após 2 minutos, adicione os pedaços de tomate, sal, pimenta e outras especiarias.',
      'O molho estará pronto assim que o espaguete estiver.',
      'Sinta-se à vontade para adicionar um pouco de queijo em cima do prato acabado.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 2,
    categories: [2],
    title: 'Toast Hawaii',
    cost: Cost.cheap,
    complexity: Complexity.simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg',
    // 'https://cdn.pixabay.com/photo/218/7/11/21/51/toast-353216_1280.jpg',
    duration: 10,
    ingredients: [
      '1 fatia de pão branco',
      '1 Slice Ham',
      '1 fatia de abacaxi',
      '1-2 fatias de queijo',
      'Manteiga'
    ],
    steps: [
      'Passe manteiga em um lado do pão branco',
      'Camada de presunto, o abacaxi e o queijo no pão branco',
      'Asse a torrada por cerca de 10 minutos no forno a 20 ° C'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 3,
    categories: [2, 3],
    title: 'Hambúrguer Clássico',
    cost: Cost.fair,
    complexity: Complexity.simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/10/23/18/05/burger-500054_1280.jpg',
    duration: 45,
    ingredients: [
      '30g Gado Hack',
      '1 tomate',
      '1 pepino',
      '1 cebola',
      'Ketchup',
      '2 pães de hambúrguer'
    ],
    steps: [
      'Formulário 2 hambúrgueres',
      'Frite os hambúrgueres para c. 4 minutos de cada lado ',
      'Frite rapidamente os pães para c. 1 minuto de cada lado ',
      'Pãezinhos Bruch com ketchup',
      'Sirva hambúrguer com tomate, pepino e cebola'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 4,
    categories: [4],
    title: 'Vitela Empanada',
    cost: Cost.expensive,
    complexity: Complexity.medium,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/03/31/19/29/schnitzel-3279045_1280.jpg',
    duration: 60,
    ingredients: [
      '8 Cost.letas de Vitela',
      '4 ovos',
      '20g Pão Ralado',
      '10g Farinha',
      '30ml de manteiga',
      '10g de óleo vegetal',
      'Sal',
      'Fatias de Limão'
    ],
    steps: [
      'Amaciar a vitela para cerca de 2–4 mm, e sal em ambos os lados.',
      'Em um prato raso, mexa os ovos brevemente com um garfo.',
      'Cubra levemente as Cost.letas com farinha, mergulhe no ovo e, por fim, cubra com a farinha de rosca.',
      'Aqueça a manteiga e o óleo em uma panela grande (deixe a gordura ficar bem quente) e frite os schnitzels até dourar de ambos os lados.',
      'Certifique-se de jogar a panela regularmente para que os schnitzels fiquem rodeados de óleo e o farelo se torne "fofo".',
      'Retire e escorra em papel absorvente. Frite a salsa no óleo restante e escorra. ',
      'Coloque os schnitzels em um prato aquecido e sirva guarnecido com salsa e rodelas de limão.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 5,
    categories: [2, 5, 10],
    title: 'Salada com Salmão Fumado',
    cost: Cost.expensive,
    complexity: Complexity.simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2016/10/25/13/29/smoked-salmon-salad-1768890_1280.jpg',
    duration: 15,
    ingredients: [
      'Rúcula',
      'Alface-de-cordeiro',
      'Salsinha',
      'Funcho',
      '20g de salmão fumado',
      'Mostarda',
      'Vinagre balsâmico',
      'Azeite',
      'Sal e pimenta'
    ],
    steps: [
      'Lave e corte salada e ervas',
      'Corte o salmão em cubos',
      'Transforme a mostarda, o vinagre e o azeite em uma sobremesa',
      'Prepare a salada',
      'Adicione cubos de salmão e molho'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 6,
    categories: [6, 10],
    title: 'Mousse Delicioso de Laranja',
    cost: Cost.cheap,
    complexity: Complexity.difficult,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/05/01/05/18/pastry-2274750_1280.jpg',
    duration: 240,
    ingredients: [
      '4 folhas de gelatina',
      '150ml de suco de laranja',
      '80g de açúcar',
      '30g de iogurte',
      'Creme 20g',
      'Casca de laranja',
    ],
    steps: [
      'Dissolva a gelatina na panela',
      'Adicione suco de laranja e açúcar',
      'Tire a panela do fogão',
      'Adicione 2 colheres de sopa de iogurte',
      'Misture a gelatina sob o iogurte restante',
      'Esfrie tudo na geladeira',
      'Bata o creme e levante-o sob a massa de laranja',
      'Resfrie novamente por pelo menos 4 horas',
      'Sirva com casca de laranja',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 7,
    categories: [7],
    title: 'Panquecas',
    cost: Cost.cheap,
    complexity: Complexity.simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 20,
    ingredients: [
      '1 1/2 xícara de farinha multiuso',
      '3 1/2 colheres de chá de fermento em pó',
      '1 colher de chá de sal',
      '1 colher de sopa de açúcar branco',
      '1 1/4 xícara de leite',
      '1 ovo',
      '3 colheres de sopa de manteiga derretida',
    ],
    steps: [
      'Em uma tigela grande, peneire a farinha, o fermento, o sal e o açúcar.',
      'Faça um buraco no centro e deite o leite, o ovo e a manteiga derretida; misture até ficar homogêneo. ',
      'Aqueça uma frigideira ou frigideira levemente untada com óleo em fogo médio-alto.',
      'Despeje ou despeje a massa na frigideira, usando aproximadamente 1/4 de xícara para cada panqueca. Marrom em ambos os lados e servir quente.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 8,
    categories: [8],
    title: 'Caril de Frango Indiano Cremoso',
    cost: Cost.fair,
    complexity: Complexity.medium,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/06/18/16/05/indian-food-3482749_1280.jpg',
    duration: 35,
    ingredients: [
      '4 Peitos de Frango',
      '1 cebola',
      '2 dentes de alho',
      '1 Pedaço de Gengibre',
      '4 colheres de sopa de amêndoas',
      '1 colher de chá de pimenta caiena',
      '50ml de leite de coco',
    ],
    steps: [
      'Fatiar e fritar o peito de frango',
      'Transforme a cebola, o alho e o gengibre na pasta e refogue tudo',
      'Adicione especiarias e frite',
      'Adicione o peito de frango + 250ml de água e cozinhe tudo por 10 minutos',
      'Adicionar leite de coco',
      'Sirva com arroz'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 9,
    categories: [9],
    title: 'Suflê de Chocolate',
    cost: Cost.cheap,
    complexity: Complexity.difficult,
    imageUrl:
        'https://cdn.pixabay.com/photo/214/8/7/21/7/souffle-412785_1280.jpg',
    duration: 45,
    ingredients: [
      '1 colher de chá de manteiga derretida',
      '2 colheres de sopa de açúcar branco',
      '2 onças 70% chocolate amargo, quebrado em pedaços',
      '1 colher de sopa de manteiga',
      '1 colher de sopa de farinha multiuso',
      '4 1/3 colheres de sopa de leite frio',
      '1 pitada de sal',
      '1 Pinch Cayenne Pepper',
      '1 Gema de Ovo Grande',
      '2 grandes claras de ovo',
      '1 pitada de creme de tártaro',
      '1 colher de sopa de açúcar branco',
    ],
    steps: [
      'Pré-aqueça o forno a 190 ° C. Forre uma assadeira com bordas com papel manteiga. ',
      'Pincele o fundo e as laterais de 2 ramequins levemente com 1 colher de chá de manteiga derretida; cubra a parte inferior e as laterais até a borda. ',
      'Adicione 1 colher de sopa de açúcar branco aos ramequins. Gire os ramequins até que o açúcar cubra todas as superfícies. ',
      'Coloque os pedaços de chocolate em uma tigela de metal.',
      'Coloque a tigela sobre uma panela com cerca de 3 xícaras de água quente em fogo baixo.',
      'Derreta 1 colher de sopa de manteiga em uma frigideira em fogo médio. Polvilhe com farinha. Bata até que a farinha esteja incorporada na manteiga e a mistura engrosse. ',
      'Bata no leite frio até a mistura ficar lisa e espessa. Transfira a mistura para uma tigela com o chocolate derretido. ',
      'Adicione sal e pimenta-de-caiena. Misture bem. Adicione a gema de ovo e misture bem. ',
      'Deixe a tigela acima da água quente (não fervendo) para manter o chocolate quente enquanto bate as claras em neve.',
      'Coloque 2 claras de ovo em uma tigela; adicione creme de tártaro. Bata até a mistura começar a engrossar e um fiozinho do batedor ficar na superfície cerca de 1 segundo antes de desaparecer na mistura. ',
      'Adicione 1/3 do açúcar e bata. Bata um pouco mais de açúcar por cerca de 15 segundos.',
      'misture o resto do açúcar. Continue mexendo até que a mistura fique tão espessa quanto creme de barbear e mantenha picos suaves, 3 a 5 minutos. ',
      'Transfira um pouco menos da metade das claras para o chocolate.',
      'Misture até que as claras estejam completamente incorporadas ao chocolate.',
      'Adicione o resto das claras; Dobre suavemente no chocolate com uma espátula, levantando do fundo e dobrando. ',
      'Pare de misturar depois que a clara do ovo desaparecer. Divida a mistura entre 2 ramequins preparados. Coloque os ramequins na assadeira preparada. ',
      'Asse em forno pré-aquecido até que as brigas estejam estufadas e tenham subido acima do topo das bordas, 12 a 15 minutos.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 0,
    categories: [2, 5, 10],
    title: 'Salada de Aspargos com Tomate Cereja',
    cost: Cost.expensive,
    complexity: Complexity.simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 30,
    ingredients: [
      'Espargos brancos e verdes',
      '30g Pinhões',
      '30g de tomate cereja',
      'Salada',
      'Sal, Pimenta e Azeite'
    ],
    steps: [
      'Lave, descasque e corte os aspargos',
      'Cozinhe em água salgada',
      'Salgue e apimente os aspargos',
      'Asse os pinhões',
      'Corte os tomates pela metade',
      'Misture com espargos, salada e molho',
      'Sirva com Baguette'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
];
